#!/usr/bin/env perl
use strict;
use warnings;

my $VAR1 = {
          'messages' => 440,
          'words' => {
                       'S' => 1,
                       'Funjet' => 1,
                       'sausage' => 26,
                       'Suites' => 3,
                       'my' => 9,
                       'buy' => 559,
                       'Sofas' => 2,
                       'http://toleranceforsomadrugnsf.blogspot.com' => 1,
                       'Mexican' => 2,
                       'http://3bphenterminerwh.blogspot.com' => 1,
                       'http://erokakkoii.org/mdm2/gyakunaka/' => 2,
                       'furtado' => 25,
                       'Guitars' => 1,
                       'http://www.munetsex.com/' => 1,
                       'shut' => 9,
                       'nelly' => 25,
                       'http://www.mutfall.com/' => 1,
                       'Pages' => 1,
                       'http://www.i-kusuri.jp/levitra' => 1,
                       'Cotta' => 1,
                       'Corolla' => 3,
                       'http://www.i-kusuri.jp/viagra' => 1,
                       '1977' => 1,
                       'download' => 43,
                       'tramadol' => 33,
                       'Vacation' => 1,
                       'http://www.geisya.or.jp/~takutaku/)' => 2,
                       'cheap' => 39,
                       'generico' => 34,
                       'watch' => 17,
                       'C' => 1,
                       'http://genericviagrafromcanadassc.blogspot.com' => 1,
                       'http://whitehourse.net/sehuretyokoubin/' => 1,
                       'http://comparecialisandviagratit.blogspot.com' => 1,
                       'http://whitehourse.net/kissme/' => 3,
                       'http://orderadipexphenteriminefastyew.blogspot.com' => 1,
                       'replica' => 17,
                       'Buy' => 73,
                       'http://mexicanpharmacyvaliumxht.blogspot.com' => 1,
                       'http://chikubi-kanjiru.com/mdm2/deep/' => 1,
                       'valium' => 50,
                       'propecia' => 28,
                       'Generic' => 26,
                       'Viagra' => 36,
                       'online' => 276,
                       'Countertop' => 1,
                       '2006' => 1,
                       'http://erokakkoii.org/mdm2/gyakudai/' => 3,
                       'Atv' => 1,
                       'Real' => 2,
                       'For' => 1,
                       'xanax' => 16,
                       'Yaris' => 1,
                       'Sale' => 1,
                       'Pick' => 1,
                       'http://phentermineonlinebuyphenterrbr.blogspot.com' => 1,
                       'Service' => 1,
                       'Highlander' => 2,
                       'levitra' => 69,
                       'Lawyers' => 1,
                       'order' => 1,
                       'sample' => 28,
                       'drug' => 77,
                       'California' => 1,
                       'mp3' => 203,
                       'Floor' => 1,
                       'Law' => 1,
                       'Cheapest' => 26,
                       's' => 1,
                       'discount' => 28,
                       'Customer' => 1,
                       'http://whitehourse.net/beautyclub/' => 1,
                       'http://mushusei.biz/mdm2/pinky/' => 4,
                       'cent' => 40,
                       'metallica' => 15,
                       'Florida' => 2,
                       'Box' => 1,
                       'Free' => 2,
                       'generica' => 34,
                       'http://ip.tosp.co.jp/i.asp?!=notaddicted' => 7,
                       'Tires' => 1,
                       'free' => 52,
                       'http://www.westjr.co.jp/news/newslist/article/1173527_799.html' => 1,
                       'Phonebook' => 1,
                       'akon' => 15,
                       'invitation' => 9,
                       'Sony' => 1,
                       'Pizzahut' => 1,
                       "\x{ff1e}\x{78ba}\x{8a8d}\x{30ed}\x{30b0}" => 3,
                       'http://www.i-kusuri.jp/cialis' => 1,
                       'big' => 26,
                       '1992' => 1,
                       '37' => 34,
                       'Hawthorne' => 1,
                       'http://pumpupthevaliumlyricsvim.blogspot.com' => 1,
                       'timbaland' => 15,
                       'http://www.hmv.co.jp/product/wmaplay.asp?tn=us%2Fuswm2%2F592%2F336592%5F2%5F10%2Easx%3Fobj%3Dv10207' => 1,
                       'eminem' => 15,
                       'Carisle' => 1,
                       'Rentals' => 1,
                       'http://somaimitrexviagralevitrayou.blogspot.com' => 1,
                       'park' => 15,
                       'u2' => 15,
                       'http://whitehourse.net/hitodumahimitu/' => 1,
                       'Vacations' => 2,
                       'http://decimusmaximusmeridiasxwj.blogspot.com' => 1,
                       'http://somabarechestcalendarfty.blogspot.com' => 1,
                       'ringtones' => 52,
                       'Apple' => 1,
                       'xmas' => 9,
                       'Toyoto' => 1,
                       'cialis' => 422,
                       'Tone' => 1,
                       'http://whitehourse.net/chupa/' => 1,
                       'cheapest' => 9,
                       'ringtone' => 9,
                       'enya' => 15,
                       'Tile' => 2,
                       'http://vicodindosageforacutepainpam.blogspot.com' => 1,
                       'http://www.nnn.co.jp/news/080203/20080203002.html' => 1,
                       'Online' => 1,
                       'http://www.treaming.net/modules/bulletin/article.php?storyid=1292' => 1,
                       'Comfort' => 1,
                       'Ringtones' => 2,
                       'phentermine' => 34,
                       'Trd' => 1,
                       'http://www.freepeople.jp/' => 1,
                       'http://whitehourse.net/tensinohane/' => 1,
                       'Toyota' => 7,
                       'Celica' => 1,
                       'Vintage' => 1,
                       'Donato' => 1,
                       'Com' => 1,
                       'wedding' => 9,
                       '50' => 40,
                       'wording' => 9,
                       'romance' => 9,
                       'http://whitehourse.net/sexygirl2/' => 1,
                       'Truck' => 1,
                       'http://fasterviagraworkingcay.blogspot.com' => 1,
                       'http://painpilladdictiontramadolxop.blogspot.com' => 1,
                       'http://xanaxnoprescription180ddx.blogspot.com' => 1,
                       'uk' => 77,
                       'http://sound-powder.com/' => 1,
                       'http://genericadipexonlylep.blogspot.com' => 1,
                       'Music' => 1,
                       'Inn' => 2,
                       'http://carisoprodolsoma0czj.blogspot.com' => 1,
                       'http://chikubi-kanjiru.com/mdm2/babaname/' => 1,
                       'http://www.npo-mirai.net/3/newpage3.html' => 1,
                       'http://mushusei.biz/mdm2/rori15/' => 2,
                       'http://viagra35008iju.blogspot.com' => 1,
                       'http://sanfranciscoapartmentssomarjv.blogspot.com' => 1,
                       'downloads' => 9,
                       'Ring' => 1,
                       'Cialis' => 27,
                       'Estate' => 2,
                       'chemical' => 9,
                       'viagra' => 653,
                       'http://genericviagrasaleslpb.blogspot.com' => 1,
                       'generic' => 133,
                       'Terra' => 1,
                       'http://whitehourse.net/sweetlove/' => 3,
                       'rihanna' => 15,
                       'pizza' => 26,
                       'Tiles' => 2,
                       '5mg' => 34,
                       'up' => 9,
                       'Zithromax' => 28,
                       'Order' => 1,
                       'Pizza' => 1,
                       'linkin' => 15,
                       'http://www.salculture.com' => 14,
                       'Jennifer' => 1,
                       'http://onlinedoctorconsultanttobulcm.blogspot.com' => 1,
                       'And' => 2,
                       'White' => 1,
                       'http://www.jrwtrading.jp/trainbox/bts_2100357.html' => 1,
                       'Verizon' => 1,
                       'Country' => 1,
                       '4' => 1,
                       'Up' => 1,
                       '2003' => 1
                     }
        };

my $words = {};
foreach my $key (keys %{ $VAR1->{words} }) {
    my $lkey = lc $key;
    if ($words->{$lkey}) {
        $words->{$lkey} += $VAR1->{words}->{$key};
    }
    else {
        $words->{$lkey} = $VAR1->{words}->{$key};
    }
}

my @sorted = sort { $words->{$b} <=> $words->{$a} } keys(%{ $words });
foreach my $key (@sorted) {
    my $ln = log($words->{$key}) / log(10);
    print $ln, ", ", $words->{$key}, ", $key\n";
}
